version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432

  summarizerbot:
    container_name: summarizerbot
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn summarizerbot.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/app/summarizerbot/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./.env.prod.db
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/summarizerbot/staticfiles
    ports:
      - 1337:80
    depends_on:
      - summarizerbot

volumes:
  postgres_data:
  static_volume: