version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  chatbot:
    container_name: chatbot
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

