version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432

  chatbot:
    container_name: chatbot
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn chatbot.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./.env.prod.db
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 1337:80
    depends_on:
      - chatbot

