version: '3.8'

services:
  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    volumes:
      - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    ports:
      - "4040:4040"
    command: [ "ngrok", "http", "localhost:8080" ]
